global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: kafka-exporter
    static_configs:
      - targets:
          - kafka-exporter:9308

  - job_name: burrow-exporter
    static_configs:
      - targets:
          - burrow-exporter:9817
