[client-profile.default]
client-id="burrow-demo-kraft"
kafka-version="3.6.0"

[cluster.local]
class-name="kafka"
servers=["kafka:29092"]
client-profile="default"
topic-refresh=20
offset-refresh=5
groups-reaper-refresh=20

[consumer.local]
class-name="kafka"
cluster="local"
servers=["kafka:29092"]
client-profile="default"
group-allowlist="^demo-.*"
group-denylist=""

[httpserver.default]
address=":8000"

[storage.default]
class-name="inmemory"
workers=20
intervals=10
expire-group=86400
min-distance=1

[evaluator.default]
class-name="caching"
expire-cache=5
minimum-complete=0.6
